services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dteam-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dteam
      - PORT=5000
      - JWT_SECRET=your-secret-key-here
      - EMAIL_USER=your-email-here
      - EMAIL_PASS=your-password-here
    depends_on:
      - mongodb
    networks:
      - dteam-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dteam-network

networks:
  dteam-network:
    driver: bridge

volumes:
  mongodb_data: